version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
      day: monday
    open-pull-requests-limit: 3
    ignore:
      - dependency-name: aws-cdk-lib
        update-types: [version-update:semver-major]
      - dependency-name: constructs
        update-types: [version-update:semver-major]
      - dependency-name: "@aws-cdk/*"
        update-types: [version-update:semver-major]
    groups:
      cdk:
        patterns:
          - aws-cdk*
          - "@aws-cdk/*"
          - constructs

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    open-pull-requests-limit: 2
